### PR TITLE
Fetaure/skip asset update 2

### PR DESCRIPTION
**Pull request by schmunk42**
The only drawback is, that the parent method is copied, because of one line.

But performance looks even better and issues with local paths and duplicates copies do not occur so far.

### CODE REVIEW

**Comment by schmunk42** [comment]
I need to check the tests, I wonder why the coverage is down, because it's actually the same code?!

**Comment by schmunk42** [comment]
related #251

**Comment by schmunk42** [comment]
@francoispluchino Sorry, I got it why coverage is down :) The used code is from composer.

Any advice how to proceed with this. I think a PR on composer side might take some time.

**Comment by francoispluchino** [comment]
@schmunk42 I'll take care of this PR this weekend.

**Comment by schmunk42** [comment]
That would be awesome. 
I've also tested the PR in several of our projects without further problems, such as duplicates in cache.

We still might consider to mark this feature as experimental in 1.4.0.

**Comment by francoispluchino** [comment]
@schmunk42 I will take care of your PR start next week. Is it possible to fix the tests before?

**Comment by francoispluchino** [comment]
Thanks!

**Pull request merged**
