### PR TITLE
Fix "Unknown downloader type: npm-signature" exception

### LINKED ISSUE #321: Problems installing NPM-assets
since a few days i get errors when trying to update/install npm-asset dependencies

It's trying to update to `npm-asset/moment` v2.22.1

```
  - Removing npm-asset/moment (2.22.0)

  [InvalidArgumentException]
  Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, r
  ar, tar, gzip, xz, phar, file, path.
```

I don't know if this is the correct place to report this, if not i'm sorry.

```
composer --version
Composer version 1.6.4 2018-04-13 12:04:24
```
and
```
fxp/composer-asset-plugin v1.4.2 NPM/Bower Dependency Manager for Composer
```

### PR DESCRIPTION
**Pull request by hypeJunction**
Dist entry resolution is now restricted to downloader types
known by composer. Effectively this means that composer-asset-plugin
will skip all dist entries that link to custom vendor protocol
implementations, e.g. npm-signature.

Fixes #321

Replaces #323

### CODE REVIEW

**Comment by francoispluchino** [comment]
Thank you for your PR, but can you use the tool [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) to respect the code style? I still have to add the doc for contributions.

1. Download/Install the tool
2. Run the command: `$ php php-cs-fixer.phar fix`

**Comment by hypeJunction** [comment]
Well, cs-fixer fixed unrelated cs violations...

**Comment by francoispluchino** [comment]
Ok, new rules have been introduced since the last commit. Can you keep only the code fixing the bug for this PR, and if you wish, propose another PR for the CS? Otherwise I will do this last....

I could quickly merge your PRs. Thank you.

**Comment by francoispluchino** [comment]
@hypeJunction Thank you!

**Pull request merged**
