### PR TITLE
Fix "Unknown downloader type: npm-signature" exception.

### PR DESCRIPTION
**Pull request by Zaporozhec7**
Issue: https://github.com/fxpio/composer-asset-plugin/issues/321

### CODE REVIEW

**Comment by SamMousa** [comment]
@francoispluchino what do you think of this solution?

**Comment by remizyaka** [comment]
any thoughts on when this will be available?

**Comment by francoispluchino** [comment]
@Zaporozhec7 Please fix the tests so that I can merge your PR.

**Comment by hypeJunction** [comment]
I can fix the tests. Will send a PR shortly.

**Comment by francoispluchino** [comment]
Replaced by #324.

**Pull request closed without merging**
